import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import serviceRoutes from './service.routes';
import orderRoutes from './order.routes';
import walletRoutes from './wallet.routes';
import adminRoutes from './admin.routes';
import agentRoutes from './agent.routes';
import notificationRoutes from './notification.routes';
import ticketRoutes from './ticket.routes';
import tenantRoutes from './tenant.routes';
import subscriptionRoutes from './subscription.routes';
import kycRoutes from './kyc.routes';
import twoFactorRoutes from './twoFactor.routes';
import referralRoutes from './referral.routes';
import apiKeyRoutes from './apiKey.routes';
import webhookRoutes from './webhook.routes';
import activityLogRoutes from './activityLog.routes';
import fraudRoutes from './fraud.routes';
import analyticsRoutes from './analytics.routes';
import exportRoutes from './export.routes';
import templateRoutes from './template.routes';
import chatRoutes from './chat.routes';
import aiInsightsRoutes from './aiInsights.routes';
import { authenticate, authorize } from '@/middleware/auth';

const router = Router();

router.use('/auth', authRoutes);
router.use('/user', authenticate, userRoutes);
router.use('/services', serviceRoutes);
router.use('/orders', authenticate, orderRoutes);
router.use('/wallet', authenticate, walletRoutes);
router.use('/admin', authenticate, authorize('admin'), adminRoutes);
router.use('/agent', authenticate, authorize('agent'), agentRoutes);
router.use('/notifications', authenticate, notificationRoutes);
router.use('/tickets', authenticate, ticketRoutes);
router.use('/tenants', authenticate, authorize('admin'), tenantRoutes);
router.use('/subscriptions', authenticate, subscriptionRoutes);
router.use('/kyc', authenticate, kycRoutes);
router.use('/2fa', twoFactorRoutes);
router.use('/referrals', authenticate, referralRoutes);
router.use('/api-keys', authenticate, apiKeyRoutes);
router.use('/webhooks', authenticate, webhookRoutes);
router.use('/activity-logs', authenticate, activityLogRoutes);
router.use('/fraud', authenticate, authorize('admin'), fraudRoutes);
router.use('/analytics', authenticate, analyticsRoutes);
router.use('/exports', authenticate, exportRoutes);
router.use('/templates', authenticate, templateRoutes);
router.use('/chat', authenticate, chatRoutes);
router.use('/ai-insights', authenticate, aiInsightsRoutes);

export default router;
